- website/source/docs/builders/vultr.html.md
Renamed doc file + added example
#5
> renamed doc file + added example

- .goreleaser.yml
- .travis.yml
- vendor/github.com/hashicorp/packer/helper/builder/testing/testing.go
- vendor/modules.txt
Updated TravisCI + GoReleaser
#8
> Travis + GoReleaser

- CHANGELOG.md
> v1.0.0 release

- CHANGELOG.md
Release for v1.0.1
Releases
#15
> release for v1.0.1

- .goreleaser.yml
- .travis.yml
> Travis go update

- CHANGELOG.md
release for v1.0.2
Releases
#17 
#18
> release v1.0.2

- CHANGELOG.md
Release for v1.0.3
Releases #23
> release for v1.0.3

- .travis.yml
- go.mod
- go.sum
- vendor/github.com/hashicorp/packer/packer/build.go
- vendor/github.com/hashicorp/packer/packer/provisioner.go
- vendor/github.com/hashicorp/packer/template/interpolate/i.go
- vendor/github.com/hashicorp/packer/template/interpolate/render.go
- vendor/github.com/hashicorp/packer/template/parse.go
- vendor/github.com/hashicorp/packer/version/version.go
- vendor/github.com/vultr/govultr/.gitignore
- vendor/github.com/vultr/govultr/CHANGELOG.md
- vendor/github.com/vultr/govultr/govultr.go
- vendor/github.com/vultr/govultr/load_balancer.go
- vendor/github.com/vultr/govultr/object_storage.go
- vendor/modules.txt
Updating deps and travis just to keep it up to date
> Updating deps

- CHANGELOG.md
> release for v1.0.4

- CHANGELOG.md
Release for v1.0.5
Releases #33 #34 #30 #32
> release for v1.0.5

- CHANGELOG.md
Release for v1.0.6
Resolves #38, #37
> release for v1.0.6

- CHANGELOG.md
Release for v1.0.7
#43 
#42 
#41
> release for v1.0.7

- CHANGELOG.md
Release for v1.0.8
Releases #45
> release for v1.0.8

- CHANGELOG.md
> Release 1.0.9

- CHANGELOG.md
Release for v1.0.11
#59 
#58 
#56
> release for v1.0.11

- .github/workflows/nightly-acceptance.yml
> night acc tests

- CHANGELOG.md
> release for v1.0.12

- CHANGELOG.md
> release for v1.0.13

- CHANGELOG.md
> release for v1.0.14

- CHANGELOG.md
> release for v1.0.15

- .github/workflows/nightly-acceptance.yml
- .goreleaser.yml
- .travis.yml
- CHANGELOG.md
- Makefile
Bumping Packer to v2.0.0 to align with govultr v2.0.0 for API v2
> Release v2.0.0

- go.mod
- go.sum
- vendor/github.com/hashicorp/hcl/v2/CHANGELOG.md
- vendor/github.com/vultr/govultr/v2/.codecov.yml
- vendor/github.com/vultr/govultr/v2/CHANGELOG.md
- vendor/github.com/vultr/govultr/v2/govultr.go
- vendor/github.com/vultr/govultr/v2/instance.go
- vendor/github.com/vultr/govultr/v2/user.go
- vendor/modules.txt
Created new PR instead of using #97 
#97
> Updating HCL + GoVultr Deps

- website/source/docs/builders/vultr.html.md
Updating the packer doc. Links back to api v2 docs and cleans up typing mistmatches
#95
> updating packer doc

- CHANGELOG.md
Release for v2.0.1
Releases all dep updates
> release for v2.0.1

- .github/workflows/notify-pr.yml
- .github/workflows/notify-release.yml
GHA for notifications on PRs/Releases
> gha for notifications

- go.mod
- go.sum
- vendor/github.com/vultr/govultr/v2/CHANGELOG.md
- vendor/github.com/vultr/govultr/v2/README.md
- vendor/github.com/vultr/govultr/v2/account.go
- vendor/github.com/vultr/govultr/v2/application.go
- vendor/github.com/vultr/govultr/v2/backup.go
- vendor/github.com/vultr/govultr/v2/bare_metal_server.go
- vendor/github.com/vultr/govultr/v2/block_storage.go
- vendor/github.com/vultr/govultr/v2/domain_records.go
- vendor/github.com/vultr/govultr/v2/domains.go
- vendor/github.com/vultr/govultr/v2/firewall_group.go
- vendor/github.com/vultr/govultr/v2/firewall_rule.go
- vendor/github.com/vultr/govultr/v2/govultr.go
- vendor/github.com/vultr/govultr/v2/instance.go
- vendor/github.com/vultr/govultr/v2/iso.go
- vendor/github.com/vultr/govultr/v2/load_balancer.go
- vendor/github.com/vultr/govultr/v2/network.go
- vendor/github.com/vultr/govultr/v2/object_storage.go
- vendor/github.com/vultr/govultr/v2/os.go
- vendor/github.com/vultr/govultr/v2/plans.go
- vendor/github.com/vultr/govultr/v2/regions.go
- vendor/github.com/vultr/govultr/v2/reserved_ip.go
- vendor/github.com/vultr/govultr/v2/snapshot.go
- vendor/github.com/vultr/govultr/v2/ssh_key.go
- vendor/github.com/vultr/govultr/v2/startup_script.go
- vendor/github.com/vultr/govultr/v2/user.go
- vendor/modules.txt
https://github.com/vultr/packer-builder-vultr/pull/104
> GoVultr Dep

- CHANGELOG.md
> release for v2.1.0

- CHANGELOG.md
Release for v2.2.1
releases #115
> release for v2.2.1

- CHANGELOG.md
> release for v2.3.0

- Makefile
- builder/vultr/builder_acc_test.go
Some nightly builds can timeout. Bump the timeouts.
> update nightly timeouts

- CHANGELOG.md
- main.go
> release for v2.3.1

- CHANGELOG.md
- docs/README.md
- main.go
> release for v2.3.2

- CHANGELOG.md
- docs/README.md
- main.go
Release for v2.4.0
#140 #141 #142
> release for v2.4.0

- CHANGELOG.md
- docs/README.md
- main.go
> Release for v2.4.2

- .github/workflows/release.yml
This PR will add the automatic releaser workflow to the packer repo. The new workflow will allow use to quickly and automatically deploy new releases.
> Add auto-releaser

- CHANGELOG.md
- docs/README.md
- main.go
- HCL v2 from 2.10.1 to 2.11.1 [#165](https://github.com/vultr/packer-builder-vultr/pull/165)
- GoVultr from 2.10.0 to 2.12.0 [#164](https://github.com/vultr/packer-builder-vultr/pull/164)
- Packer-plugin-sdk from 0.2.7 to 0.2.9 [#160](https://github.com/vultr/packer-builder-vultr/pull/160)
> Release v2.4.3 #patch

- .github/workflows/release.yml
This PR fixes the regex for the auto releaser
> Fixed regex for releaser

- .github/workflows/nightly-acceptance.yml
- .github/workflows/release.yml
This PR will add the Mattermost notifications for the nightly acceptance tests.
> Added Mattermost Notifications

- README.md
Replaces travis badge with gha
> Replace travis badge

- CHANGELOG.md
- docs/README.md
- main.go
Release for v2.4.4 
#174 
#170
> Release v2.4.4 #patch

- Makefile
This PR should resolve the build errors we are seeing in the workflow
> Fixed workflow

- .github/workflows/release.yml
Replace action per: https://github.com/hashicorp/ghaction-import-gpg
> Replace unsupported gpg workflow action

- CHANGELOG.md
> Release v2.5.0 #minor

- .goreleaser.yml
Add OpenBSD build to goreleaser
closes #244
> Add OpenBSD build to goreleaser

- .github/workflows/notify-pr.yml
- .github/workflows/release.yml
Fix mattermost notifications after major version update
> Update mattermost notification action

- .github/workflows/release.yml
> Update workflow to use GITHUB_OUTPUT envvar
